### ISSUE TITLE
How to make ajax request based on inputs?

### ISSUE THREAD

**Issue by qodesmith** [qodesmith/artist-hub#3]
@harimohanraj89 @WilliamfShaw @bigtone1284 

A typical ajax put request might look something like this:

```
$.ajax({
  url: '/users/1',
  method: 'PUT',
  data: {
    name: 'Qodesmith',
    age: '55',
    coolness: '9001'
  }
});
```
Let's assume those are the only 3 fields a user has. I'd like to allow a user to update their info. The interface will have an input box for each field (name, age, and coolness).

When I click submit, I'd like only the fields that received an input to be included in the PUT request. Are you guys aware of how to do this? My javascript file will have to have the route already coded with, say, jQuery functions for the data values - `name: $('#name').val()`. If the value is empty, the value will become an empty string, replacing the previous users field info for an empty string. Is there a way to avoid this?

**Comment by bigtone1284** [comment]
@qodesmith idea.  Use the prexisting values as placeholders in this form.  We have done this before in class.

**Comment by qodesmith** [comment]
@bigtone1284 Ahhhhh, good sir. You are the man. Didn't even think of that.

**Comment by bigtone1284** [comment]
Or, write a bit of logic (control flow checking for empty strings) that does not add empty strings to the data object.

**Comment by bigtone1284** [comment]
I am going to close this issue.  cool?

**Comment by qodesmith** [comment]
Cool. Thanks bro.
