### ISSUE TITLE
Getting heroku up and running

### ISSUE THREAD

**Issue by qodesmith** [qodesmith/artist-hub#5]
I've successfully pushed to heroku. I've edited the config.json & index.js files accordingly as well as created a database. I've checked the logs but don't understand the errors (along with the thesis of other data it gives me).

I need Heroku to be up and running first thing today as it's the only way I can start testing my integration with Amazon S3. S3 functionality is my mvpppppppp!

**Comment by qodesmith** [comment]
Ooops, forgot to tag you gaiz... @harimohanraj89 @bigtone1284 @DrRobotmck @WilliamfShaw

**Comment by bigtone1284** [comment]
@harimohanraj89 @bigtone1284 @DrRobotmck @WilliamfShaw 

taken
